name: tpot-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - bokeh=2.3.1
  - brotlipy=0.7.0
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.5
  - click=7.1.2
  - cloudpickle=1.6.0
  - cryptography=3.4.7
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask=2021.4.0
  - dask-core=2021.4.0
  - dask-glm=0.2.0
  - dask-ml=1.8.0
  - deap=1.3.1
  - distributed=2021.4.0
  - freetype=2.10.4
  - fsspec=0.9.0
  - heapdict=1.0.1
  - jinja2=2.11.3
  - joblib=1.0.1
  - jpeg=9d
  - kiwisolver=1.3.1
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libgomp=9.3.0
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - libxgboost=1.3.3
  - llvmlite=0.36.0
  - locket=0.2.0
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - matplotlib-base=3.4.1
  - msgpack-python=1.0.2
  - multipledispatch=0.6.0
  - ncurses=6.2
  - numba=0.53.1
  - numpy=1.20.2
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.2.4
  - partd=1.2.0
  - pillow=8.1.2
  - pip=21.0.1
  - psutil=5.8.0
  - py-xgboost=1.3.3
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.9.2
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytz=2021.1
  - pyyaml=5.4.1
  - readline=8.0
  - scikit-learn=0.24.1
  - scikit-mdr=0.4.4
  - scipy=1.6.2
  - setuptools=49.6.0
  - six=1.15.0
  - skrebate=0.62
  - sortedcontainers=2.3.0
  - sqlite=3.35.4
  - stopit=1.1.2
  - tblib=1.7.0
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - tpot=0.11.7
  - tqdm=4.60.0
  - typing_extensions=3.7.4.3
  - tzdata=2021a
  - update_checker=0.18.0
  - wheel=0.36.2
  - xgboost=1.3.3
  - xz=5.2.5
  - yaml=0.2.5
  - zict=2.0.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - chardet==3.0.4
    - idna==2.8
    - notify-run==0.0.13
    - pyqrcode==1.2.1
    - requests==2.22.0
    - urllib3==1.25.11
